# -*- coding: utf-8 -*-


######################
#DO NOT EDIT THIS FILE
######################

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QHBoxLayout,
    QLabel, QLineEdit, QPushButton, QRadioButton,
    QSizePolicy, QTextBrowser, QVBoxLayout, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(581, 491)
        self.horizontalLayoutWidget = QWidget(Dialog)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 10, 381, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.lineEdit = QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName(u"lineEdit")

        self.horizontalLayout.addWidget(self.lineEdit)

        self.pushButton = QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(u"pushButton")

        self.horizontalLayout.addWidget(self.pushButton)

        self.textBrowser = QTextBrowser(Dialog)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(10, 50, 381, 431))
        self.textBrowser.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.verticalLayoutWidget = QWidget(Dialog)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(410, 10, 160, 202))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(u"label")
        font = QFont()
        font.setFamilies([u"Noto Sans KR"])
        font.setPointSize(9)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label)

        self.radioButton_5 = QRadioButton(self.verticalLayoutWidget)
        self.radioButton_5.setObjectName(u"radioButton_5")

        self.verticalLayout.addWidget(self.radioButton_5)

        self.radioButton_4 = QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName(u"radioButton_4")

        self.verticalLayout.addWidget(self.radioButton_4)

        self.radioButton = QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName(u"radioButton")

        self.verticalLayout.addWidget(self.radioButton)

        self.radioButton_6 = QRadioButton(self.verticalLayoutWidget)
        self.radioButton_6.setObjectName(u"radioButton_6")

        self.verticalLayout.addWidget(self.radioButton_6)

        self.radioButton_3 = QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName(u"radioButton_3")

        self.verticalLayout.addWidget(self.radioButton_3)

        self.radioButton_7 = QRadioButton(self.verticalLayoutWidget)
        self.radioButton_7.setObjectName(u"radioButton_7")

        self.verticalLayout.addWidget(self.radioButton_7)

        self.radioButton_2 = QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName(u"radioButton_2")

        self.verticalLayout.addWidget(self.radioButton_2)

        self.verticalLayoutWidget_2 = QWidget(Dialog)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(410, 220, 160, 98))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_2)

        self.radioButton_8 = QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_8.setObjectName(u"radioButton_8")

        self.verticalLayout_2.addWidget(self.radioButton_8)

        self.radioButton_9 = QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_9.setObjectName(u"radioButton_9")

        self.verticalLayout_2.addWidget(self.radioButton_9)

        self.radioButton_10 = QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_10.setObjectName(u"radioButton_10")

        self.verticalLayout_2.addWidget(self.radioButton_10)

        self.verticalLayoutWidget_3 = QWidget(Dialog)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(410, 330, 160, 124))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName(u"label_3")
        font1 = QFont()
        font1.setFamilies([u"Noto Sans KR"])
        font1.setBold(True)
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_3)

        self.radioButton_11 = QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_11.setObjectName(u"radioButton_11")

        self.verticalLayout_3.addWidget(self.radioButton_11)

        self.radioButton_13 = QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_13.setObjectName(u"radioButton_13")

        self.verticalLayout_3.addWidget(self.radioButton_13)

        self.radioButton_12 = QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_12.setObjectName(u"radioButton_12")

        self.verticalLayout_3.addWidget(self.radioButton_12)

        self.radioButton_14 = QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_14.setObjectName(u"radioButton_14")

        self.verticalLayout_3.addWidget(self.radioButton_14)

        self.horizontalLayoutWidget_2 = QWidget(Dialog)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(410, 460, 161, 22))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.checkBox = QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox.setObjectName(u"checkBox")

        self.horizontalLayout_2.addWidget(self.checkBox)


        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Send", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"[ ComPort ]", None))
        self.radioButton_5.setText(QCoreApplication.translate("Dialog", u"COM3", None))
        self.radioButton_4.setText(QCoreApplication.translate("Dialog", u"COM4", None))
        self.radioButton.setText(QCoreApplication.translate("Dialog", u"COM5", None))
        self.radioButton_6.setText(QCoreApplication.translate("Dialog", u"COM6", None))
        self.radioButton_3.setText(QCoreApplication.translate("Dialog", u"COM7", None))
        self.radioButton_7.setText(QCoreApplication.translate("Dialog", u"COM8", None))
        self.radioButton_2.setText(QCoreApplication.translate("Dialog", u"COM9", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"[ \ubcf4\ub4dc \ub808\uc774\ud2b8 ]", None))
        self.radioButton_8.setText(QCoreApplication.translate("Dialog", u"9600", None))
        self.radioButton_9.setText(QCoreApplication.translate("Dialog", u"38400", None))
        self.radioButton_10.setText(QCoreApplication.translate("Dialog", u"115200", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"[ \ubb38\uc790\uc5f4\uc758 \ub05d \ubb38\uc790 ]", None))
        self.radioButton_11.setText(QCoreApplication.translate("Dialog", u"No line ending", None))
        self.radioButton_13.setText(QCoreApplication.translate("Dialog", u"\\n [New line]", None))
        self.radioButton_12.setText(QCoreApplication.translate("Dialog", u"\\r [carrage return]", None))
        self.radioButton_14.setText(QCoreApplication.translate("Dialog", u"\\n + \\r", None))
        self.checkBox.setText(QCoreApplication.translate("Dialog", u"\uc790\ub3d9 \uc2a4\ud06c\ub864", None))
    # retranslateUi

